[package]
name = "muxr_client"
version = "0.1.0"
authors = ["Sam Wilson <tecywiz121@hotmail.com>"]

[dependencies]
error-chain = "0.12.0"
muxr = { version = "0.1.0", path = "../muxr" }
termion = "1.5.1"

[[bin]]
name = "muxr"
path = "src/main.rs"
