[package]
name = "muxr_client"
version = "0.1.0"
authors = ["Sam Wilson <tecywiz121@hotmail.com>"]
edition = "2018"

[dependencies]
error-chain = "0.12.0"
muxr_core = { version = "0.1.0", path = "../muxr_core" }
termion = "1.5.1"
